name: Documentation CI
on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Lint markdown
        run: npx markdownlint '**/*.md'
      
      - name: Check spelling
        run: npx cspell '**/*.md'
      
      - name: Validate links
        run: npx markdown-link-check '**/*.md'