app:
  name: "Multi-Tech Test App"
  version: "1.0.0"
  
backend:
  host: "0.0.0.0"
  port: 5000
  # BUG: Missing database_url - will fail if code expects it
  # database_url: "postgresql://user:pass@localhost:5432/db"
  
frontend:
  host: "0.0.0.0"
  port: 3000

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"