name: Python Build, Lint & Test

on:
  workflow_dispatch: {}  # Manual trigger

jobs:
  python-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          flake8 .
          black --check .

      - name: Run unit tests
        run: |
          pytest tests --cov=app

      - name: Run backend build
        run: |
          python -m compileall .

      - name: Build Docker image
        run: |
          docker build -t movie-app-backend -f Dockerfile .
