jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: development

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Run tests
        run: npm test

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install Snyk
        run: npm install snyk --save-dev

      - name: Run Snyk to check for vulnerabilities
        run: npx snyk test

  deploy:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Deploy application
        run: |
          # Deployment command here
          while ! <check-deployment-status-command>; do
            echo "Waiting for deployment to stabilize..."
            sleep 10
          done
          echo "Deployment is stable."