name: Deploy

on:
  workflow_dispatch: {}  # manually trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy backend via Docker
        run: |
          docker build -t multi-tech-backend .
          docker run -d -p 5000:5000 multi-tech-backend

      - name: Show running containers
        run: docker ps
