name: Documentation CI
on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Lint markdown
        run: npx markdownlint '**/*.md'
        continue-on-error: true
      
      - name: Check spelling
        run: npx cspell '**/*.md'
        continue-on-error: true
      
      - name: Validate links
        run: npx markdown-link-check README.md
        continue-on-error: true

      - name: Aggregate results
        run: |
          if [ -f markdownlint-results.txt ]; then
            echo "Markdown linting errors found."
          fi
          if [ -f cspell-results.txt ]; then
            echo "Spelling errors found."
          fi
          if [ -f markdown-link-check-results.txt ]; then
            echo "Broken links found."
          fi