name: Documentation CI
on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci

  lint-markdown:
    runs-on: ubuntu-latest
    needs: lint-docs
    steps:
      - name: Lint markdown
        run: npx markdownlint '**/*.md'

  check-spelling:
    runs-on: ubuntu-latest
    needs: lint-docs
    steps:
      - name: Check spelling
        run: npx cspell '**/*.md'

  validate-links:
    runs-on: ubuntu-latest
    needs: lint-docs
    steps:
      - name: Validate links
        run: npx markdown-link-check README.md