name: Documentation CI
on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linting: [markdownlint, cspell, markdown-link-check]
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Run linting
        run: |
          if [ "${{ matrix.linting }}" == "markdownlint" ]; then
            npx markdownlint '**/*.md'
          elif [ "${{ matrix.linting }}" == "cspell" ]; then
            npx cspell '**/*.md'
          elif [ "${{ matrix.linting }}" == "markdown-link-check" ]; then
            npx markdown-link-check README.md
          fi
        continue-on-error: false