name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build --cache-from=myapp:latest -t myapp:latest .

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install linters
        run: pip install flake8 black
      - name: Run linters
        run: flake8 . && black --check .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging server..."