jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to AWS
        run: |
          aws s3 sync ./dist s3://my-bucket --region ${{ secrets.AWS_REGION }} || exit 1
          aws cloudfront create-invalidation --distribution-id my-distribution-id --paths "/*" --region ${{ secrets.AWS_REGION }} || exit 1