name: Cleanup Old Artifacts
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed'
            });
            
            const cutoff = Date.now() - (30 * 24 * 60 * 60 * 1000);
            const oldRuns = runs.data.workflow_runs.filter(run => 
              new Date(run.created_at).getTime() < cutoff
            );
            
            for (const run of oldRuns) {
              try {
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              } catch (error) {
                console.error(`Failed to delete run ${run.id}: ${error.message}`);
                // Implement retry logic if necessary
              }
            }
            
            console.log(`Deleted ${oldRuns.length} old workflow runs`);

  cleanup_branches:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Clean up old branches
        run: |
          git fetch --prune --depth=1
          git branch -r --merged | grep -v main | sed 's/origin\///' | xargs -r git push origin --delete